### ISSUE TITLE
Web UI: select UI theme

### ISSUE THREAD

**Issue by sergeyt** [edu-xored/calendar#10]
Alternatives:
* https://react-bootstrap.github.io/ - we can try to use one of https://bootswatch.com/ theme
* http://react-toolbox.com/ - material design
* other CSS theme

We need to select the CSS theme to get UI with consistent design.

**Comment by sergeyt** [comment]
Please feel free to send your suggestions.

**Comment by CodersGit** [comment]
Maybe, that? http://semantic-ui.com/
It [has React integration](http://semantic-ui.com/introduction/integrations.html).

**Comment by sergeyt** [comment]
@CodersGit semantic-ui is good one, lets use it if on one will offer better alternative.

**Comment by sergeyt** [comment]
lets go with semantic-ui with material theme
