### ISSUE TITLE
Web UI: PageHeader react component with main navigation

### ISSUE THREAD

**Issue by sergeyt** [edu-xored/calendar#12]
This component will be used across all pages.

Navigation links:
- Calendars
- Reports
- Admin

And user avatar with dropdown menu with the following actions:
- Profile
- Logout

**Comment by CodersGit** [comment]
Эти ссылки должны быть фиксированно только такими или сделать массив, откуда они будут подтягиваться? Также делать ли проверку на права и залогиненность пользователя (хотябы зачатки)?

**Comment by CodersGit** [comment]
И еще: где и как мы должны добавлять к странице PageHeader? В `index.tsx` аналогично `Root` (или, может, как-то по-другому?) или на каждой странице отдельно если он там нужен?

**Comment by sergeyt** [comment]
@CodersGit
> Эти ссылки должны быть фиксированно только такими или сделать массив, откуда они будут подтягиваться?

делай массив, можешь пока харкодить в компоненте

> Эти ссылки должны быть фиксированно только такими или сделать массив, откуда они будут подтягиваться?

отдельная задача, можешь завести и делать или другу предложи :)

> И еще: где и как мы должны добавлять к странице PageHeader? В index.tsx аналогично Root (или, может, как-то по-другому?) или на каждой странице отдельно если он там нужен?

пока можно копировать, потом зарефакторим с помощью react-router когда появится много страниц

**Comment by CodersGit** [comment]
Осталась бага, почему-то менюшка с никнеймом остается слева. также текстовое поле в массиве container пушится после него, хотя в коде это происходит, наоборот, до этого. Почему так - не знаю.

**Comment by sergeyt** [comment]
@CodersGit создавай PR, на багу заведи ишуй. Сейчас главное функциональность. Баги потом набросимся поправим.
