### ISSUE TITLE
Server: LDAP basic authentication

### ISSUE THREAD

**Issue by sergeyt** [edu-xored/calendar#6]
This is required feature. It should be implemented as [express middleware](http://expressjs.com/en/guide/writing-middleware.html). Also note that as part of we need to select appropriate LDAP nodejs client.

**Comment by sergeyt** [comment]
See https://github.com/jshttp/basic-auth

**Comment by moonlightnvkz** [comment]
What about [ldapjs](http://ldapjs.org/) with [this typings](https://github.com/types/npm-ldapjs)?
I also thought about [Passportjs](http://passportjs.org/). As for me, it rather simple and has good integration with express, but no typings.

**Comment by sergeyt** [comment]
@moonlightnvkz ldapjs looks like good choice. Actually we could try to use it as LDAP server in automated integration tests. Use of passportjs is ok too, but implementation of simple basic auth is also enough. Missing typings is not a problem, we can write them later. Please go ahead.

**Comment by moonlightnvkz** [comment]
@sergeyt Тот самый вопрос по реализации.
Вот есть у меня сервер и 2 клиента: один обычный, другой - рут. Пока пользователя два (один рут, другой - нет), особых проблем нет: если логин рут - используем рут-клиент и биндим к серверу, если обычный - используем другой и не биндим, ограничивая его тем самым в правах до поиска и сравнения. Соответственно, когда вызываем логаут для рута делаем анбинд, но вот для обычного делать нечего. Но как тогда узнать, авторизован ли он сейчас или нет? Хранить для пользователя булевый флаг на сервере и обнулять его при логауте? А если пользователей несколько? Булевый флаг решает проблему с обычными пользователями, но что делать с несколькими рут-пользователями? В вызов анбинд нельзя запихать логин/пароль и, если я правильно понимаю, при каждом новом бинде поля логин/пароль перезаписываются, то есть если поступит несколько биндов с одного клиента, то анбинд будет выполнен только для последнего. Хранить копии клиентов для каждого рут-пользователя? 

Хотя, можно использовать 1 рут-клиент с фиксированной парой логин/пароль, создавать его при первом вызове и использовать его для всякой подходящей пары логин/пароль, считать каждый вызов, а при логауте уменьшать счетчик и вызывать анбинд, если на счетчике ноль...

**Comment by sergeyt** [comment]
@moonlightnvkz давай в конфиге задавать логин/пароль/т.д для создания LDAP клиента, достаточного чтобы осуществлять поиск пользователя и проверку пароля - рут пока не нужен

**Comment by sergeyt** [comment]
@moonlightnvkz каков статус по этой задаче? Когда сможешь доделать? Тебе вроде немного осталось. Если не понял моих коментариев, давай обсудим в телеграмме.

**Comment by moonlightnvkz** [comment]
@sergeyt До пятницы будет. Мне действительно чуть-чуть осталось. За вчера-сегодня разобрался с sequalize. Если сегодня останется время, перепишу серверную часть (хотя бы частично). Если нет, завтра точно будет.

**Comment by sergeyt** [comment]
@moonlightnvkz отлично!
